# Generated by Django 2.0 on 2018-07-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.IntegerField(max_length=10)),
                ('music_pic', models.CharField(max_length=200)),
                ('listen_num', models.CharField(max_length=20)),
                ('song_title', models.CharField(max_length=100)),
                ('song_user', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'music_list',
            },
        ),
    ]
