# Generated by Django 2.0 on 2018-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0002_musiclist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musiclist',
            name='music_id',
            field=models.CharField(max_length=10),
        ),
    ]
