# Generated by Django 2.0 on 2018-07-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0004_auto_20180706_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_pic', models.CharField(max_length=200)),
                ('movie_name', models.CharField(max_length=60)),
                ('movie_score', models.CharField(max_length=60)),
                ('movie_des', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'movie_list',
            },
        ),
    ]
