# Generated by Django 2.0 on 2018-07-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0005_movielist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='jump_href',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='movie_des',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
