# Generated by Django 2.0 on 2018-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0006_auto_20180707_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='movie_score',
            field=models.CharField(default='Null', max_length=60),
        ),
    ]
