# Generated by Django 2.0 on 2018-07-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0007_auto_20180707_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=60)),
                ('movie_pic', models.CharField(max_length=200)),
                ('movie_intract', models.CharField(max_length=300)),
                ('movie_download_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'film_down',
            },
        ),
    ]
