# Generated by Django 2.0 on 2018-07-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0011_pythonpos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonShanghai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('job_require', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=20)),
                ('work_city', models.CharField(max_length=20)),
                ('work_exp', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('compname', models.CharField(max_length=30)),
                ('compdetail_href', models.CharField(max_length=200)),
                ('workinfo2', models.CharField(max_length=60)),
                ('head_pic', models.CharField(max_length=200)),
                ('workinfo3', models.CharField(max_length=60)),
                ('public_time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'python_shanghai',
            },
        ),
    ]
