# Generated by Django 2.0 on 2018-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0012_pythonshanghai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('pic_src', models.CharField(max_length=200)),
                ('pic_href', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=500)),
                ('tabs', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'health',
            },
        ),
    ]
