# Generated by Django 2.0 on 2018-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0014_auto_20180709_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthy',
            name='ptime',
            field=models.CharField(default='今天', max_length=20),
        ),
    ]
