# Generated by Django 2.0 on 2018-07-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0016_smile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=32)),
                ('icon', models.CharField(default='default.png', max_length=64)),
                ('user_token', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'world_userinfo',
            },
        ),
    ]
