# Generated by Django 2.0 on 2018-07-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy', '0017_userinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='smile',
            table='smile1',
        ),
    ]
